<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EducationalPlatform.Application\EducationalPlatform.Application.csproj" />
    <ProjectReference Include="..\EducationalPlatform.Domain\EducationalPlatform.Domain.csproj" />
  </ItemGroup>

</Project>
